### ISSUE TITLE
radiobutton with ngModel

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-buttons#4]
Hi,

How works the radiobutton with ngModel? When we have 3 options the value must be change. There are no examples with ngModel.

Regards
j.nord

**Comment by Shanmugarajakaliappan** [comment]
Hi @j-nord,

We faced issue “**RadioButton value changed while using ngModel**” while preparing sample based on your request. So, we have logged a defect report for the same and the fix will be available in our December 14, 2017 release. We will update you with the sample once the fix for the issue is available until then we appreciate your patience.

Regards,
Shanmugaraja K

**Comment by vinoth-Kumar-S** [comment]
Hi @j-nord ,

Thanks for your patience.

We are glad to announce that our _**v15.4.22-preview**_ release is rolled out successfully. In this release, we have added the fix for **RadioButton value changed while using ngMode**l issue.

https://github.com/syncfusion/ej2-buttons/releases/tag/v15.4.22-preview 

We have created the sample for RadioButton with ngmodel. Please refer the below link,

https://github.com/SyncfusionSamples/ej2-radioButton-ngModel 

Please let us know if you have any queries.

Regards,
Vinoth Kumar S
